// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DXApplication3.Models;

public partial class Lead
{
    public int Id { get; set; }

    public string Aname { get; set; }

    public string Type { get; set; }

    public DateTime? Due { get; set; }

    public DateTime TimeStamp { get; set; }

    public int? Complete { get; set; }

    public int? ContactId { get; set; }

    public int? AssignedTo { get; set; }

    public int? Priority { get; set; }

    public DateTime? Created { get; set; }

    public string CreatedBy { get; set; }

    public string Memo { get; set; }

    public decimal? Value { get; set; }

    public string Stage { get; set; }

    public int Exp { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Org { get; set; }

    public string Ref { get; set; }

    public string EmailMemo { get; set; }

    public string Source { get; set; }

    public bool? LeadSeen { get; set; }

    public string Activitiescol { get; set; }

    public string Locale { get; set; }

    public string Po { get; set; }

    public decimal? Profit { get; set; }

    public DateTime LeadArchieveDate { get; set; }
    [NotMapped]
    public bool Archieved => LeadArchieveDate < DateTime.Now.AddMonths(-18);
    public List<LeadEvent> LeadEvents { get; set; }
}